# Generated by Django 2.2.16 on 2023-04-09 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20230408_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст коментария', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(blank=True, help_text='Пост к которому относится коментрарий', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='posts.Post', verbose_name='Комент')),
            ],
            options={
                'verbose_name': ('Комментарий',),
                'verbose_name_plural': 'Comment',
                'ordering': ('-created',),
            },
        ),
    ]
